from collections.abc import AsyncIterator
from typing import Any, Protocol

from app.domain.entities import (
    CalendarEvent,
    CalendarEventProposal,
    ChatCompletionResult,
    ChatMessage,
    DocumentMetadata,
    EmailDraft,
    EmailMessage,
    EmailSummary,
    ToolCallRequest,
    UserPreference,
    UserProfile,
)


class HealthCheckRepository(Protocol):
    """Abstract boundary the application layer depends on.

    infrastructure provides the concrete implementation (e.g. a SQLAlchemy
    ping against Postgres); application never imports that implementation
    directly — only this interface.
    """

    async def check_database(self) -> bool: ...


class GraphTokenProvider(Protocol):
    """Exchanges the inbound user JWT for a Graph-scoped access token via
    the On-Behalf-Of flow. The API never stores or forwards the user's
    original Graph credentials — only this short-lived derived token."""

    async def get_graph_token(self, user_oid: str, user_assertion: str) -> str: ...


class GraphClient(Protocol):
    """Abstract boundary over Microsoft Graph. application depends on this,
    never on the concrete httpx-based implementation."""

    async def get_my_profile(self, access_token: str) -> UserProfile: ...


class ChatClient(Protocol):
    """Abstract boundary over the LLM. application depends on this, never
    on the concrete Azure OpenAI SDK implementation."""

    def stream_completion(self, messages: list[ChatMessage]) -> AsyncIterator[str]: ...

    async def complete_with_tools(
        self, messages: list[ChatMessage], tools: list[dict[str, Any]]
    ) -> ChatCompletionResult:
        """Non-streaming: the model either answers directly or asks to call
        one or more tools. Tool-calling needs the full response to inspect
        `tool_calls`, so this can't be a stream — the final natural-language
        reply (after tool results are fed back) uses stream_completion."""
        ...


class GraphMailClient(Protocol):
    """Abstract boundary over Microsoft Graph mail endpoints."""

    async def list_recent_emails(
        self, access_token: str, top: int, unread_only: bool
    ) -> list[EmailSummary]: ...

    async def get_email(self, access_token: str, message_id: str) -> EmailMessage: ...

    async def create_draft_reply(
        self, access_token: str, message_id: str, body: str
    ) -> EmailDraft:
        """Creates a reply draft in the user's Drafts folder. Never sends
        it — sending would require a separate, explicit user action that
        no tool call can trigger on its own."""
        ...


class GraphCalendarClient(Protocol):
    """Abstract boundary over Microsoft Graph calendar endpoints. Only
    invoked by the explicit calendar-confirmation endpoint — never by a
    tool call the model can trigger directly."""

    async def create_event(self, access_token: str, proposal: CalendarEventProposal) -> CalendarEvent: ...


class ToolProvider(Protocol):
    """Abstract boundary over tool discovery and execution. The concrete
    implementation talks to one or more MCP servers over stdio — application
    has no idea tools are backed by external processes at all, let alone
    which ones, or that Graph/Azure AI Search are involved for any
    particular tool. Adding a new tool means adding a server to the registry
    the implementation reads; nothing here or in application/chat.py changes.
    """

    async def get_tool_specs(self) -> list[dict[str, Any]]:
        """OpenAI-format function specs, discovered dynamically from
        whichever MCP servers are registered."""
        ...

    async def execute_tool(self, tool_call: ToolCallRequest, context: dict[str, str]) -> str:
        """Dispatches to whichever server exposes this tool, injecting
        whichever `context` entries that server declared it needs (e.g. a
        Graph access token, or the caller's user_oid for document
        isolation) as environment variables — never as tool arguments the
        model could see or fill in itself. Tools needing nothing from
        `context` just ignore it."""
        ...


class BlobStorageClient(Protocol):
    """Abstract boundary over blob storage. application depends on this,
    never on the concrete Azure Storage SDK / Azurite implementation."""

    async def upload(self, blob_path: str, content: bytes) -> None: ...


class DocumentRepository(Protocol):
    """Abstract boundary over document metadata storage (Postgres). The
    actual OCR/chunk/embed/index pipeline runs out-of-process in the
    blob-triggered Azure Function — this repository is how both the API
    and the Function report/read a document's status without needing to
    know about each other."""

    async def create_document(
        self, document_id: str, user_oid: str, filename: str, blob_path: str
    ) -> DocumentMetadata:
        """document_id is generated by the caller (not the database) so it
        can be embedded in the blob path before the row exists — the
        blob-triggered Function needs that id to know which row to update
        once processing finishes."""
        ...

    async def list_documents(self, user_oid: str) -> list[DocumentMetadata]: ...

    async def get_owner(self, document_id: str) -> str | None:
        """Returns the user_oid that owns this document, or None if it
        doesn't exist — same ownership-check pattern as ConversationRepository."""
        ...


class PreferenceRepository(Protocol):
    """Abstract boundary over durable user preferences (Postgres). Unlike
    tool results, preferences are loaded directly by SendChatMessageUseCase
    into the system prompt on every turn — not gated behind a tool call —
    so a preference stated once actually influences a brand-new
    conversation automatically, which is the whole point of this being
    "long-term" memory rather than just more conversation history."""

    async def get_preferences(self, user_oid: str) -> list[UserPreference]: ...

    async def set_preference(self, user_oid: str, key: str, value: str) -> None:
        """Upserts — setting an existing key's value again just updates it."""
        ...


class ConversationRepository(Protocol):
    """Abstract boundary over conversation history storage. The concrete
    implementation persists durably to Postgres and read-through caches
    the recent window in Redis — application only ever sees this interface,
    so it has no idea storage is split across two systems."""

    async def create_conversation(self, user_oid: str) -> str:
        """Returns the new conversation's id."""
        ...

    async def get_recent_messages(self, conversation_id: str, limit: int) -> list[ChatMessage]: ...

    async def append_message(self, conversation_id: str, message: ChatMessage) -> None: ...

    async def get_owner(self, conversation_id: str) -> str | None:
        """Returns the user_oid that owns this conversation, or None if it
        doesn't exist. Callers must check this before reading or appending
        to a conversation_id supplied by the client — otherwise one user
        could read or write another user's chat history by guessing/reusing
        a conversation id."""
        ...
