"""add documents table

Revision ID: 599f3921fbe1
Revises: e70c953a8b37
Create Date: 2026-07-15 18:30:54.792891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '599f3921fbe1'
down_revision: Union[str, None] = 'e70c953a8b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_oid', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('blob_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_oid'), 'documents', ['user_oid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_oid'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
