"""add preferences table

Revision ID: 7f70e129edb3
Revises: 599f3921fbe1
Create Date: 2026-07-19 21:59:53.993193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f70e129edb3'
down_revision: Union[str, None] = '599f3921fbe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_oid', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_oid', 'key', name='uq_preferences_user_oid_key')
    )
    op.create_index(op.f('ix_preferences_user_oid'), 'preferences', ['user_oid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preferences_user_oid'), table_name='preferences')
    op.drop_table('preferences')
    # ### end Alembic commands ###
