"""add tool calling columns to messages

Revision ID: e70c953a8b37
Revises: c53a2cd92837
Create Date: 2026-07-15 12:11:35.783263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e70c953a8b37'
down_revision: Union[str, None] = 'c53a2cd92837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('tool_call_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('messages', 'name')
    op.drop_column('messages', 'tool_call_id')
    op.drop_column('messages', 'tool_calls')
    # ### end Alembic commands ###
